### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eternaleclipse** [tmpout/tmpout.github.io#11]
I'm using Crowdin to organize the Hebrew translation efforts, and as far as I understand, they basically sponsor open-source with a free membership, but require a license, which appears to be missing from this repo. I suggest adding a `LICENSE` file.

Also, what license does it make sense to use here? I imagine attribution, non-commercial and share-alike would be kind of important, so maybe CC-BY-NC-SA?

**Comment by netspooky** [comment]
Thank you for the suggestion. We have applied CC-BY-NC-SA 4.0 to our website. https://github.com/tmpout/tmpout.github.io/blob/main/LICENSE
